Spotter filtering does not split the search string accordingly to camel syntax
pharo-spec/NewTools pull request #347
Opened 2022-02-17 16:12 UTC by carolahp

This change makes the query results more precise by preventing spotter to split the search string accordingly to camel case.

For example:
Before: the query 'StoreDisk' returned 'DiskStore'
Now: the query 'StoreDisk' does not return 'DiskStore'

2022-02-18 12:55 UTC, tesonep requested changes
I don't understand why is it best to have like this.
What are the use cases that are improved?

2022-02-18 15:01 UTC, carolahp commented
> What are the use cases that are improved?

Users normally use camelcase to search (because it's the convention for names in Pharo) while not knowing that when the query is written in camel case, it is split as if it was separated by spaces (eg: the query 'StoreDisk' is equivalent to 'Store Disk').

Because of this behavior, Spotter returns too many irrelevant results when users use camel case to search.
This implementation makes spotter results more precise when users use camel case, which is most of the time. If users want to search different words, they still can use spaces between words

2022-03-08 15:04 UTC, MarcusDenker commented
I got at PharoDays the comment, too, that spotter shows too many useless hits to the point of being useless (for that programmer)

2023-02-03 09:22 UTC, jecisc commented
I sometimes find that useful. 
Often I know globaly what I'm looking for but I don't know the exact name. Writing what I think it is with camel case help me when I don't put things in the right order. 

But maybe those kind of results should be sorted after what matches exactly what we enter.

2023-03-02 08:45 UTC, demarey commented
@carolahp @tesonep What do we do with this PR?
My opinion is that spotter does not work well. If you know the exact selector and type it in spotter, you have a lot of noise around (selectors or classes with pieces of the selector or more).
I would be in favor to do not split on camel case. In this case, this PR could be ok (but some commented code needs to be removed). The previous search behaviour is still usable by using spaces instead of camel case

2023-07-02 16:23 UTC, Ducasse commented
Ping!

2023-07-02 16:23 UTC, Ducasse commented
Can we take a decision on this issue?

2024-06-11 15:09 UTC, merged

2024-06-11 15:10 UTC, MarcusDenker commented
This was now merged in the Pharo10 branch.