362 accesses to debugger session from debugger need refactoring
pharo-spec/NewTools pull request #366
Opened 2022-05-04 13:56 UTC by adri09070

Fixes #362
In the class `StDebugger` which represents the GUI of the debugger, the debug session was sometimes manipulated directly by the GUI.

This shouldn't be the case as the logic of the debugger shouldn't be mixed with the GUI, as a debugger should be able to exist without a GUI. Furthermore, the logic of the debugger should be in a completely different object, so that we can change the GUI of the debugger without the risk of breaking the debugger's logic.

As a result, all direct session accesses and manipulations are done through the debugger action model, whose goal is to perform actions on the debug session. Thus, the `StDebugger` now delegates to the action model that accesses/manipulates the session; where before `StDebugger` accessed/manipulated the debug session directly.

Furthermore, all these accesses/manipulations are tested

2022-05-06 09:35 UTC, StevenCostiou requested changes

2022-05-06 09:35 UTC, StevenCostiou commented on src/NewTools-Debugger-Tests/StDebuggerActionModelTest.class.st
> +]
Also check that the new topContext == contextChanged

2022-05-06 09:35 UTC, StevenCostiou commented on src/NewTools-Debugger-Tests/StDebuggerActionModelTest.class.st
> +
I would like a comment that explains the structure of the stack => how does the stack evolve with the step until?

2022-05-06 09:35 UTC, StevenCostiou commented on src/NewTools-Debugger-Tests/StDebuggerActionModelTest.class.st
> +	self assert: debugActionModel sessionStack equals: debugActionModel session stack
rename sessionStack to stack?

2022-05-06 09:35 UTC, StevenCostiou commented on src/NewTools-Debugger-Tests/StDebuggerActionModelTest.class.st
> +	newStack := debugActionModel stackOfSize: oldStack size + 13.
Explain magic number please :)

2022-05-06 09:35 UTC, StevenCostiou commented on src/NewTools-Debugger-Tests/StDebuggerActionModelTest.class.st
> +	newStack := debugActionModel stackOfSize: oldStack size + 13.
Explain magic number please :)

2022-05-06 09:35 UTC, StevenCostiou commented on src/NewTools-Debugger-Tests/StDebuggerTest.class.st
> +		equals: debugger debuggerActionModel exception
identicalTo:

2022-05-06 09:35 UTC, StevenCostiou commented on src/NewTools-Debugger/StDebugger.class.st
> +{ #category : #accessing }
Can we move to a new protocol => "stack - helpers"

2022-05-06 09:35 UTC, StevenCostiou commented on src/NewTools-Debugger/StDebugger.class.st
> +	selectionInterval := selectionInterval := self debuggerActionModel
Typo ;)

2022-05-06 09:35 UTC, StevenCostiou commented on src/NewTools-Debugger/StDebugger.class.st
> +		                                          selectedCodeRangeForContext:
Can we have a helper?

2022-05-20 08:35 UTC, StevenCostiou approved these changes

2022-05-25 08:22 UTC, StevenCostiou commented
@MarcusDenker can you have a look?
I think it could be merged.

2022-05-30 13:52 UTC, MarcusDenker approved these changes

2022-05-30 13:52 UTC, merged