Adding debugger visitor to display variables from extensions (as Chest)
pharo-spec/NewTools pull request #402
Opened 2022-07-27 09:57 UTC by adri09070

This follows the PR that modified `StDebuggerContextInteractionModel` to allow to add bindings into the debugger itself: #378. This concept is used by Chest to load any object from anywhere in Pharo into the debugger: https://github.com/adri09070/Chest

Now, that Chest is able to add bindings into the debugger, I made this PR to see these bindings in the debugger inspector.

To do that, I created an extensible debugger extension visitor system. So, if any other debugger extension add variables into the debugger, we will be able to distinguish those that come from Chest and those that come from any other debugger extension.

Plus, `StDebuggerExtensionVisitor` provides hooks for every debugger extension and can be easily subclassed to perform other operations on debugger extensions.

The only doubt that I have is that I define the `visitChest:` method in `StDebuggerExtensionVisitor` and in `StDebuggerExtensionInspectorNodeBuilderVisitor`. As Chest is not in NewTools, I wonder if it would not be better to put this method as an extension method in Chest (let me know what you think but anyway, it allows you to see how it will work in Chest)

2022-11-18 14:00 UTC, StevenCostiou requested changes

2022-11-18 14:00 UTC, StevenCostiou commented on src/NewTools-Debugger/StDebuggerExtensionInspectorNodeBuilderVisitor.class.st
> +]
Should be in Chest as an extension method.

2022-11-18 14:00 UTC, StevenCostiou commented on src/NewTools-Debugger/StDebugger.class.st
> +			self code interactionModel addBinding: assoc ] ].
Review naming it is unclear

2022-11-18 14:00 UTC, StevenCostiou commented on src/NewTools-Debugger/StDebugger.class.st
Add flag: 'to refactor later'?
Ugly and unclear code.

2022-11-18 14:00 UTC, StevenCostiou commented on src/NewTools-Debugger/StDebuggerExtensionInspectorNodeBuilderVisitor.class.st
> +	^ extensionNodes == self ifTrue: [ self newCollection ] ifFalse: [ extensionNodes ]
Prefer to store the results into an inst var rather than returning data for which we cannot predict the type.

2022-11-25 08:35 UTC, adri09070 commented
all done

2022-11-25 09:10 UTC, StevenCostiou approved these changes

2022-11-25 09:10 UTC, merged