New debugger extension model to display dynamic extensions
pharo-spec/NewTools pull request #739
Opened 2024-04-09 14:30 UTC by adri09070

# New Dynamic Debugger Extension System

This PR introduces a new debugger extension model to display extensions dynamically. These "dynamic" extensions are displayed only if they are activated (that goes without saying) **and** only if we are in a specific context.

## Description of the New Debugger Extension System

The debugger extension determines if it can be displayed in a debugger via the method: 

```Smalltalk
TStDebuggerExtension>>#acceptsPredicate:  aStDebuggerContextPredicate

   ^ true "By default, a debugger extension is static"
```

This method uses the debugger's context predicate to determine if the extension should be displayed or not. **We could discuss: Should the method use a debugger as parameter instead of a context predicate?** The extension would have more parameters to decide if it should display itself or not, but is it necessary ?

This induces two big changes in the update of extensions:
- When an extension is (de)activated which sends an `StDebuggerExtensionToggleAnnouncement` to the debugger, the debugger now should consider the current context predicate,  because if it is refused by the toggled extension, the extension toggle should be ignored: it has no effect
- The context predicate can change after each action in the debugger, including steps (correct me if I'm wrong). So the extensions should be updated accordingly. Instead of just updating the instanciated presenters, we should check if there are:
  * extensions that were activated but that didn't accept the debugger context predicate until now, in which case it should be added now.
  * extensions that were activated and that did accept the debugger context predicate until now, in which case it should be removed from the extension tools.

## Introducing a New Dynamic Debugger Extension: Creating Method Extension

This debugger extension is displayed by default in the system settings:

![image](https://github.com/pharo-spec/NewTools/assets/97704417/a71eeb1d-944e-4b1d-94fd-bf57b4d51936)

This extension only appears if a DNU is raised and opens a debugger:

![image](https://github.com/pharo-spec/NewTools/assets/97704417/791da535-a1aa-4efb-b607-5e58465ed3b7)

It has the exact same function as the "Create" button in the debugger toolbar, except that this extension allows the user to create the missing method while choosing the class or trait in the class hierarchy in which it should be installed, as well as the protocol under which it should be installed.
Whereas the "Create" button creates the missing class in the class of the receiver of the missing message, under a protocol chosen by the system.

With this extension, once you create the method by clicking the "Add method" button, the method has been created, the extension is not displayed anymore, and you can then proceed the execution (or debug it, of course):

![image](https://github.com/pharo-spec/NewTools/assets/97704417/2845d1e8-838f-4ded-8084-377adbd54bbd)

2024-04-09 14:31 UTC, adri09070 commented
@StevenCostiou

2024-04-29 10:59 UTC, StevenCostiou commented
The failing test seem unrelated?
I am reveiwing the changes now.

2024-04-29 11:38 UTC, adri09070 commented
> The failing test seem unrelated? I am reveiwing the changes now.

The test fails in a fresh Pharo 13 image so it is unrelated

2024-05-03 09:42 UTC, StevenCostiou requested changes
Good for merge.
Just one minor change that would be great ;)

2024-05-03 09:42 UTC, StevenCostiou commented on src/NewTools-Debugger-Exceptions/StDebuggerMNUExtensionTest.class.st
> +	^ StDebuggerMNUExtension
Perhaps ask a MNU exception the class of the extension?

2024-05-03 09:43 UTC, StevenCostiou commented on src/NewTools-Debugger-Exceptions/StDebuggerMNUExtensionTest.class.st
> +	^ StDebuggerMNUExtension
Ok I take it back, I mixed up things.

2024-05-03 09:45 UTC, merged