Adding command to add breakpoints in the debugger
pharo-spec/NewTools pull request #807
Opened 2024-07-19 07:39 UTC by adri09070

Needs https://github.com/pharo-project/pharo/pull/16919 to be merged first

2024-07-19 07:40 UTC, adri09070 commented
@StevenCostiou

2024-07-19 07:53 UTC, StevenCostiou commented
thanks I will look at this

2024-07-23 11:19 UTC, StevenCostiou requested changes

2024-07-23 11:19 UTC, StevenCostiou commented on src/NewTools-Debugger-Commands/StBreakOnStackCommand.class.st
> +	^ 'Break on stack'
I would name it just "break"

2024-07-23 11:19 UTC, StevenCostiou commented on src/NewTools-Debugger-Commands/StBreakOnStackCommand.class.st
> +	^ #breakOnStack
Does this icon exists?
Why not #smallDebug for example?

2024-07-23 13:17 UTC, adri09070 commented
done

2024-07-26 08:49 UTC, StevenCostiou commented
The contributions are good.
We can go when tests are fixed.
There is only one related failing test, apparently there is a implemented selector that is never sent?

2024-07-26 08:54 UTC, adri09070 commented
I think this is the message send `#findContextsForMethod:`, which is implemented in the other PR that should be merged first. I saw that there is an `assert:` left that I will remove

2024-07-26 09:50 UTC, adri09070 commented
We should wait a few hours so that the build including my changes of https://github.com/pharo-project/pharo/pull/16919 has been built

2024-07-26 12:42 UTC, adri09070 commented
For me, it is good to merge

2024-07-26 12:46 UTC, merged